baseURL       = "https://rossmaryrangel.com"
languageCode  = "en-us"
title         = "Rossmary Rangel"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Biographie"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Projets"
    url     = "projets"
    weight  = 3
  [[menu.nav]]
    name    = "Enseignement"
    url     = "enseignement"
    weight  = 4
  [[menu.nav]]
    name    = "Agenda"
    url     = "agenda"
    weight  = 5
  [[menu.nav]]
    name    = "Galerie"
    url     = "galerie"
    weight  = 6
  [[menu.nav]]
    name    = "Contactez-moi"
    url     = "contact"
    weight  = 7

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Rossmary Rangel"
  author = "StaticMania"
  # Google Analytics (replace with actual GA4 measurement ID)
  googleAnalitycsID = "G-XXXXXXXXXX"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/Zrr0MZi"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Rossmary Rangel"
    tagline               = ""
    primary_button        = "Projets"
    primary_button_url    = "projets"
    secondary_button      = "Contactez-moi"
    secondary_button_url  = "contact"

  [params.projets]
    enable    = true
    title     = "Projets"
    view_project = "En savoir plus"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Travaillons ensemble"
    primary_button      = "Contactez-moi"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "projets"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Paris, France"
      phone   = "+33 (0)X XX XX XX XX"
      email   = "contact@rossmaryrangel.com"
    # Footer Sitemap
    [params.footer.sitemap]
      title   = "Sitemap"
      [[params.footer.sitemap.link]]
        name = "About Company"
        url  = "about"
      [[params.footer.sitemap.link]]
        name = "Projects"
        url  = "projets"
      [[params.footer.sitemap.link]]
        name = "Agenda"
        url  = "agenda"
      [[params.footer.sitemap.link]]
        name = "Contact"
        url  = "contact"
    # Footer Social Media
    [params.footer.social]
      title   = "Social Media"
      [[params.footer.social.link]]
        name = "Instagram"
        url  = "https://www.instagram.com/rossrangelflute/"
      [[params.footer.social.link]]
        name = "Personal Youtube"
        url  = "https://www.youtube.com/@rossmaryrangel3927"
      [[params.footer.social.link]]
        name = "GuayoyoProject Youtube"
        url  = "https://www.youtube.com/@GuayoyoProject"
    # Footer Service
    [params.footer.service]
        title       = "Rossmary Rangel:"
        description = "Artiste musicienne<br>Enseignement musical<br>Projets culturels"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
